type LatestReward @entity {
  id: String!
  rewarded: [Reward!]! # rewarded pools
  totalAmount: BigInt! # uint256
  blockTimestamp: BigInt! # Timestamp
}

type Reward @entity(immutable: true) {
  id: Bytes! # token address
  token: Bytes! # address
  amount: BigInt! # uint256
  blockTimestamp: BigInt! # Timestamp
}

type Counter @entity{
  id: String!
  value: BigInt!
}

type Pool @entity {
  id: Bytes! # address
  tokenAddress: Bytes! # address 
  tick: Int! # int24
  tickCumulativeStart: BigInt! # int54
  startTickTimestamp: BigInt! # Timestamp
  tickCumulativeEnd: BigInt! # int54
  endTickTimestamp: BigInt! # Timestamp
  twat: BigInt! # int56 expected time-weighted geometric mean tick
  sqrtPriceX96: BigInt! # uint160
  blockTimestamp: BigInt! # Timestamp
  creationTimestamp: BigInt! # Timestamp
  isRewarded: Boolean!
  score: String! # combined twat, sqrtPriceX96, tick and creationTimestamp for comparing pools. Made for lexicographic comparison
}
